services:
  evershelf:
    build: .
    container_name: evershelf
    ports:
      - "8000:80/tcp"
    env_file: stack.env
    volumes:
      # Persist database and runtime data
      - evershelf_data:/var/www/html/data
      # Mount your local .env configuration
      # - ./.env:/var/www/html/.env:ro
    command: >
      sh -c "printenv > /var/www/html/data/.env && 
             ln -sf /var/www/html/data/.env /var/www/html/.env && 
             exec apache2-foreground"
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - APP_ENV=local
      - DEVELOPMENT=true
      # - APP_CONFIG_FILE=/var/www/html/data/.env



volumes:
  evershelf_data:
    driver: local
